
local insert_list = {
    {
        id_matchup="elk",
        name="cat_mocreeps",
    },
    {
        id_matchup="cat_mocreeps",
        name="cat_mocreeps_spoopy_skittle",
    },
    {
        id_matchup="zombie",
        name="bubble_liquid",
    },
    {
        id_matchup="miner_chef",
        name="hiisi_thief",
    },
    {
        id_matchup="shotgunner",
        name="hisii_minecart",
    },
    {
        id_matchup="hiisi_minecart",
        name="hisii_minecart_tnt",
    },
    {
        id_matchup="hiisi_minecart_tnt",
        name="hisii_giga_bomb",
    },
    {
        id_matchup="scavenger_glue",
        name="hisii_engineer",
    },
    {
        id_matchup="scavenger_shield",
        name="hisii_rocketshotgun",
    },
    {
        id_matchup="alchemist",
        name="hisii_hobo",
    },
    {
        id_matchup="hisii_hobo",
        name="hisii_hobo_rich",
    },
    {
        id_matchup="shaman",
        name="shaman_greater_apotheosis",
    },
    {
        id_matchup="lasershooter",
        name="blindgazer",
    },
    {
        id_matchup="giantshooter",
        name="slime_leaker_weak",
    },
    {
        id_matchup="slime_leaker_weak",
        name="slime_leaker",
    },
    {
        id_matchup="slime_leaker",
        name="slime_teleporter",
    },
    {
        id_matchup="slime_teleporter",
        name="goo_slug",
    },
    {
        id_matchup="goo_slug",
        name="poring",
    },
    {
        id_matchup="poring",
        name="poring_magic",
    },
    {
        id_matchup="poring_magic",
        name="poring_devil",
    },
    {
        id_matchup="poring_devil",
        name="poring_holy",
    },
    {
        id_matchup="blob",
        name="blob_big",
    },
    {
        id_matchup="blob_big",
        name="blob_huge",
    },
    {
        id_matchup="ant",
        name="ant_fire",
    },
    {
        id_matchup="ant_fire",
        name="ant_suffocate",
    },
    {
        id_matchup="rat",
        name="rat_birthday",
    },
    {
        id_matchup="bigbat",
        name="ccc_bat_psychic",
    },
    {
        id_matchup="shooterflower",
        name="mudman_friendly",
    },
    {
        id_matchup="fungus",
        name="ceiling_fungus",
    },
    {
        id_matchup="ceiling_fungus",
        name="poisonmushroom",
    },
    {
        id_matchup="poisonmushroom",
        name="fungus_smoking_creep",
    },
    {
        id_matchup="fungus_giga",
        name="lukki_fungus",
    },
    {
        id_matchup="skullfly",
        name="hideous_mass",
    },
    {
        id_matchup="tentacler",
        name="tentacler_big",
    },
    {
        id_matchup="longleg",
        name="longleg_pillar",
    },
    {
        id_matchup="lukki_creepy_long",
        name="lukki_swarmling",
    },
    {
        id_matchup="lukki_dark",
        name="sunken_creature",
    },
    {
        id_matchup="sunken_creature",
        name="lukki_fire_miniboss_phase2",
    },
    {
        id_matchup="lukki_fire_miniboss_phase2",
        name="giant_centipede",
    },
    {
        id_matchup="giant_centipede",
        name="locust_swarm",
    },
    {
        id_matchup="locust_swarm",
        name="devourer_magic",
    },
    {
        id_matchup="devourer_magic",
        name="seeker",
    },
    {
        id_matchup="seeker",
        name="miniboss_pit_02",
    },
    {
        id_matchup="miniboss_pit_02",
        name="star_child",
    },
    {
        id_matchup="worm_big",
        name="worm_wall",
    },
    {
        id_matchup="worm_end",
        name="worm_mechanical",
    },
    {
        id_matchup="drone_physics",
        name="drone_status_ailment",
    },
    {
        id_matchup="drone_status_ailment",
        name="drone_mini",
    },
    {
        id_matchup="basebot_soldier",
        name="c_basebot_speeder_apotheosis",
    },
    {
        id_matchup="tank_rocket",
        name="tank_flame_apotheosis",
    },
    {
        id_matchup="firemage",
        name="wizard_firemage_greater",
    },
    {
        id_matchup="wizard_firemage_greater",
        name="watermage",
    },
    {
        id_matchup="watermage",
        name="watermage_greater",
    },
    {
        id_matchup="wizard_twitchy",    --Behold! 19 consecutive appends
        name="wizard_ambrosia\nwizard_copeseethmald\nwizard_duck\nenchanted_duck\nwizard_explosive\nwizard_jackofalltrades\nwizard_manaeater\nwizard_transmutation\nwizard_wands\nwizard_z_poly_miniboss\nwizard_corrupt_ambrosia\nwizard_corrupt_hearty\nwizard_corrupt_manaeater\nwizard_corrupt_neutral\nwizard_corrupt_swapper\nwizard_corrupt_teleport\nwizard_corrupt_twitchy\nwizard_corrupt_weaken",
    },
    {
        id_matchup="wraith_glowing",
        name="wraith_alchemy_apotheosis\nwraith_returner_apotheosis\nwraith_weirdo_shield",
    },
    {
        id_matchup="hpcrystal",
        name="whisp\nwhisp_big\nfairy_cheap\nfairy_big\nfairy_giant\nfairy_big_discord\nfairy_esoteric\nesoteric_being\nworm_esoteric",
    },
    {
        id_matchup="ethereal_being",
        name="musical_being\nmusical_being_weak",
    },
    {
        id_matchup="phantom_b",
        name="phantom_c_apotheosis\ndevourer_ghost\nghost_bow\nforsaken_eye",
    },
    {
        id_matchup="gazer",
        name="gazer_greater",
    },
    {
        id_matchup="skygazer",
        name="gazer_greater_sky\ngazer_cold_apotheosis\ngazer_greater_cold\ngazer_parasitic\ngazer_robot",
    },
    {
        id_matchup="spitmonster",
        name="sentry\ntriangle_gem",
    },
    {
        id_matchup="",
        name="",
    },
    {
        id_matchup="",
        name="",
    },
    {
        id_matchup="",
        name="",
    },
    {
        id_matchup="",
        name="",
    },
}


local path, enemies = "data/ui_gfx/animal_icons/_list.txt", {}
for enemy in ModTextFileGetContent(path):gmatch("[^\r\n]+") do
    enemies[#enemies+1] = enemy
end

-- Do your table shenanigans

ModTextFileSetContent(path, table.concat(enemies, "\n"))